import Head from 'next/head'
import Style from './layout.module.css';
import Header from '../header/header';
import Footer from '../footer/footer';
const Layout = (props) =>{

    return <main>
        <Head>
        <title>Amid Concrete</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        {props.children}
        <Footer />
    </main>
}

export default Layout;